### ISSUE TITLE
ERROR WHEN CONVERTING

### ISSUE THREAD

**Issue by PeraltaEspectre** [sliva0/tgradish#1]
I've tried using both on Windows, Linux and even Termux and it's not working anymore.  On a cell phone that I already had installed since January it is working normally, but the new installations are giving an error

-------------------------------------------------------------------------
--------------------------------------------------------------------------
ERROR

tgradish convert -i ~/000.mp4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\tgradish.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\__init__.py", line 9, in <module>
    from .converter import CmdConfig, convert_video
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\converter.py", line 7, in <module>
    from .config_model import CmdConfig, CmdParams, ArgsPlaceholder
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\config_model.py", line 77, in <module>
    class EnumFlag(CmdFlag):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\config_model.py", line 81, in EnumFlag
    @pydantic.root_validator
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\deprecated\class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\deprecated\class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.2/u/root-validator-pre-skip

-----------------------------------------------------------------------------

-----------------------------------------------------------------------------

tgradish convert -i 000.mp4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\tgradish.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\__init__.py", line 9, in <module>
    from .converter import CmdConfig, convert_video
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\converter.py", line 7, in <module>
    from .config_model import CmdConfig, CmdParams, ArgsPlaceholder
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\config_model.py", line 77, in <module>
    class EnumFlag(CmdFlag):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgradish\config_model.py", line 81, in EnumFlag
    @pydantic.root_validator
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\deprecated\class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\deprecated\class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.2/u/root-validator-pre-skip

**Comment by sliva0** [comment]
Thanks for reporting the issue.

Temporary fix:
```
pip install pydantic==1.10.2
```
I already got reports about this issue, basically there are incorrect comparing operators in the requirements.txt.

**Comment by PeraltaEspectre** [comment]
Thank you for your attention, it works perfectly now... thank you very much
