### ISSUE TITLE
Error before converting

### ISSUE THREAD

**Issue by IBTS90** [sliva0/tgradish#3]
Hi, i've got the following error but after several try I couldn't manage to go ahead, I even tried to switch to 2.2 but without luck, can you please help me out?

PS C:\Python312> tgradish convert -i ~/Plant.mp4
Output file defaults to '~\Plant.webm'.
Starting to guess bitrate on interval [0.0, 500.0] in 5 iterations...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\tgradish.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\tgradish\__init__.py", line 117, in main
    convert_cmd(args)
  File "C:\Python312\Lib\site-packages\tgradish\__init__.py", line 58, in convert_cmd
    convert_video(config, args)
  File "C:\Python312\Lib\site-packages\tgradish\converter.py", line 161, in convert_video
    output_file = guess_value(config, cmd_params, run_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tgradish\converter.py", line 114, in guess_value
    path = generate_tmp_file_path(run_info.output, f"_{fvalue}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tgradish\converter.py", line 42, in generate_tmp_file_path
    tmp_dir.mkdir(exist_ok=True)
  File "C:\Python312\Lib\pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [WinError 3] Impossibile trovare il percorso specificato: '~\\tmp'

**Comment by sliva0** [comment]
Try running your console (cmd.exe) as administrator, it's some Windows weirdness which forbids you to create folders. Also you can try to run this script in another folder, other than `C:\Python312`.

**Comment by sliva0** [comment]
I discussed this issue with some of my friends, you can ignore my previous message. In the future, please wrap your command line output in three apostrophes on separate lines, or just select pasted text and press the `Code` button with the `<>` icon above the text input in Github.

If you don't do that some special symbols, like `~` will turn into Strikethrough text, ~like that~, which is confusing to read and hard to find problems in.

Your problem is the fact that instead of the path to a file you are passing `~/Plant.mp4`, which is an impossible file path on a Windows machine. You should try drag-n-drop file that you want to convert into your console.

There is an example of the install and `spoof` command usage, but should be still useful.

https://github.com/user-attachments/assets/3ddc4da7-f1a8-49a3-b58a-42535b6fc572
